name: Deploy

# Trigger the workflow on push 
# pull request events on the production
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      
# Authenticate to the the server via ss
# and run our deployment script 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository # clone the repo to local ci workspace
        uses: actions/checkout@v2
        
      - name: SFTP Deploy
        # You may pin to the exact commit or the versio
        # uses: wlixcc/SFTP-Deploy-Action@da88a4dbe95286266bbac3c0b2b8284048d20c8f
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # username
          username: ubuntu
          # your sftp server
          server: ec2-3-89-110-123.compute-1.amazonaws.com
          # your sftp server port, default to 22
          port: 22
          # you can copy private_key from your *.pem file, keep forma
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # will put all file under this path
          local_path: ./*
          # files will copy to under remote_path
          remote_path: '/var/www/html/admin.execubod.com'
          
